apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: kafka
    spec:
      containers:
      - env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:32181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafkasvc:29092"
        - name: KAFKA_BROKER_ID
          value: "2"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        image: confluentinc/cp-kafka:5.3.0
        imagePullPolicy: ""
        name: kafka
        ports:
        - containerPort: 9092
        - containerPort: 29092
        resources: {}
      hostname: kafka
      volumes: null
status: {}
