apiVersion: v1
kind: Service
metadata:
  name: kafka-music-application
spec:
  ports:
  - name: "7070"
    port: 7070
    targetPort: 7070
  type: LoadBalancer
  selector:
    io.kompose.service: kafka-music-application
status:
  loadBalancer: {}
