apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: schema-registry
  name: schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: schema-registry
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: schema-registry
    spec:
      containers:
      - env:
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: schema-registry
        - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
          value: zookeeper:32181
        image: confluentinc/cp-schema-registry:5.5.0
        imagePullPolicy: ""
        name: schema-registry
        ports:
        - containerPort: 8081
        resources: {}
      hostname: schema-registry
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
